//LOGIN
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG';

//AUTHENTICATION
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

//CREATE USER
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'
export const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG'

//CREATE FORUM
export const CREATE_FORUM_SUCCESS = 'CREATE_FORUM_SUCCESS'
export const CREATE_FORUM_ERROR = 'CREATE_FORUM_ERROR'

//SHOW USERS
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS'
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR'

//EDIT USER
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_ERROR = 'EDIT_ERROR'
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';

//DELETE USER
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'
export const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG'

//SHOW FORUM
export const ALLFORUMS_ERROR='ALLFORUMS_ERROR'
export const ALLFORUMS_SUCCESS='ALLFORUMS_SUCCESS'

//EDIT FORUM
export const EDITFORUM_SUCCESS = 'EDITFORUM_SUCCESS'
export const EDITFORUM_ERROR = 'EDITFORUM_ERROR'
export const SHOW_EDIT_FORUM_DIALOG = 'SHOW_EDIT_FORUM_DIALOG';

//CREATE FORUM
export const SHOW_CREATE_FORUM_DIALOG ='SHOW_CREATE_FORUM_DIALOG'
export const CREATE_NEW_SUCCESS='CREATE_NEW_SUCCESS'
export const CREATE_NEW_ERROR='CREATE_NEW_ERROR'

//DELETE FORUM
export const DELETE_FORUM_SUCCESS = 'DELETE_FORUM_SUCCESS'
export const DELETE_FORUM_ERROR = 'DELETE_FORUM_ERROR'
export const SHOW_DELETEFORUM_DIALOG = 'SHOW_DELETEFORUM_DIALOG'
export const SHOW_DELETE_FORUM_DIALOG ='SHOW_DELETE_FORUM_DIALOG'
export const HIDE_FORUM_DIALOG='HIDE_FORUM_DIALOG'

//SHOW MESSAGES
export const ALLMSG_SUCCESS ='ALLMSG_SUCCESS'
export const ALLMSG_ERROR ='ALLMSG_ERROR'
export const SHOW_CREATEMSG_DIALOG ='SHOW_CREATEMSG_DIALOG'

//CREATE MESSAGE
export const CREATEMSG_SUCCESS ='CREATEMSG_SUCCESS' 
export const CREATEMSG_ERROR ='CREATEMSG_ERROR' 
export const SHOW_FORUM ='SHOW_FORUM'

//EDIT MESSAGE
export const EDIT_MESSAGE_SUCCESS ='EDIT_MESSAGE_SUCCESS' 
export const EDIT_MESSAGE_ERROR ='EDIT_MESSAGE_ERROR'
export const SHOW_MSGEDIT_DIALOG = 'SHOW_MSGEDIT_DIALOG'

//DELETE MESSAGE
export const DELETE_MESSAGE_SUCCESS ='DELETE_MESSAGE_SUCCESS' 
export const DELETE_MESSAGE_ERROR ='DELETE_MESSAGE_ERROR' 
export const SHOW_DELETEMSG_DIALOG = 'SHOW_DELETEMSG_DIALOG'

//PENDINGS
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING'
export const USER_PENDING = 'USER_PENDING'
export const FORUM_PENDING = 'FORUM_PENDING'
export const MESSAGE_PENDING ='MESSAGE_PENDING'

export const HIDE_DIALOG = 'HIDE_DIALOG'